version: '3'
services:
  api:
    hostname: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15.3-alpine
    hostname: db
    ports:
      - 5432:5432
    env_file:
      - .env.db
